language: python
python:
  - "2.7"
  - "3.4"

services:
  - postgresql

before_script:
- cp config/database.yml.travis config/database.yml

install:
  - pip install -r requirements.txt

script:
  - python manage.py test
